# I-V Curve Analysis Configuration
# This file contains configuration settings for the I-V curve analysis system

[data_processing]
# Maximum number of inverters to process
max_inverters = 10

# Include synthetic data generation for demonstration
include_synthetic = true

# Number of synthetic inverters to generate (when real data is insufficient)
max_synthetic = 3

# Data validation thresholds
min_voltage_threshold = 1.0
min_current_threshold = 0.1
min_power_threshold = 100.0

[analysis_parameters]
# I-V parameter validation ranges
voc_min = 10.0
voc_max = 1000.0
isc_min = 0.5
isc_max = 50.0
fill_factor_min = 0.3
fill_factor_max = 1.0
series_resistance_min = 0.01
series_resistance_max = 10.0
shunt_resistance_min = 10.0
shunt_resistance_max = 50000.0

[plotting]
# Plot generation settings
dpi = 300
figure_size_width = 12
figure_size_height = 10
save_plots = true
show_plots = false

[diagnostics]
# Health assessment thresholds
fill_factor_excellent = 0.82
fill_factor_good = 0.75
fill_factor_fair = 0.65
series_resistance_warning = 2.0
shunt_resistance_warning = 100.0

[synthetic_data]
# Synthetic data generation scenarios
scenarios = [
    {name = "High Performance", voc_factor = 1.05, isc_factor = 1.02, rs_factor = 0.8, rsh_factor = 1.2, power_factor = 1.08},
    {name = "Normal Operation", voc_factor = 1.0, isc_factor = 1.0, rs_factor = 1.0, rsh_factor = 1.0, power_factor = 1.0},
    {name = "Slight Degradation", voc_factor = 0.95, isc_factor = 0.97, rs_factor = 1.3, rsh_factor = 0.8, power_factor = 0.92},
    {name = "Moderate Degradation", voc_factor = 0.90, isc_factor = 0.92, rs_factor = 1.6, rsh_factor = 0.6, power_factor = 0.83},
    {name = "Soiling/Shading", voc_factor = 0.98, isc_factor = 0.85, rs_factor = 1.1, rsh_factor = 0.9, power_factor = 0.83}
]
